(function(){
'use strict';
const app=document.getElementById('app');
const DEFAULT={version:6,weight:85,waist:'',logs:[],bodyLogs:[],activities:[],checks:{},lastWorkout:'Legs 1',omronSeeded:false};
function readState(){try{const raw=localStorage.getItem('fitnessMaster');const old=raw?JSON.parse(raw):{};const s=Object.assign({},DEFAULT,old);s.logs=Array.isArray(s.logs)?s.logs:[];s.bodyLogs=Array.isArray(s.bodyLogs)?s.bodyLogs:[];s.activities=Array.isArray(s.activities)?s.activities:[];s.checks=(s.checks&&typeof s.checks==='object')?s.checks:{};if(!window.PROGRAM_ORDER.includes(s.lastWorkout))s.lastWorkout='Legs 1';return s}catch(e){return Object.assign({},DEFAULT)}}
let state=readState();
const save=()=>{try{localStorage.setItem('fitnessMaster',JSON.stringify(state))}catch(e){}};
function seedOmron(){const exists=state.bodyLogs.some(x=>x&&x.source==='Omron'&&x.dateISO==='2026-08-20T13:37');if(!exists)state.bodyLogs.push({date:'20.08.2026 13:37',dateISO:'2026-08-20T13:37',weight:'',fat:'23.7',skeletalMuscle:'33.7',waist:'',source:'Omron'});state.omronSeeded=true;save()}
seedOmron();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toLocaleDateString('tr-TR');
function shell(title,body){return `<div class="content"><h2>${title}</h2>${body}</div>`}
function nextWorkout(){const order=window.PROGRAM_ORDER;let i=order.indexOf(state.lastWorkout);return order[(i<0?0:i+1)%order.length]}
function videoLinks(e){return (e.videos||[]).map((v,i)=>`<a class="video" target="_blank" rel="noopener" href="${v[1]}">▶ Video ${i+1}: ${esc(v[0])}<span>${esc(v[2]||'')}</span></a>`).join('')}
function setCount(e){const m=String(e.sets||'').match(/^(\d+)/);return m?Math.max(1,Math.min(5,Number(m[1]))):1}
function exerciseCard(name,log){const e=window.EXERCISES[name];if(!e)return '';const n=setCount(e);let rows='';if(log){for(let i=1;i<=n;i++)rows+=`<div class="set-row"><span class="set-no">Set ${i}</span><input class="input" placeholder="kg" data-k="kg"><input class="input" placeholder="rep / m" data-k="reps"><input class="input" placeholder="RIR" data-k="rir"><button class="btn small log" data-name="${esc(name)}" data-set="${i}">Kaydet</button></div>`}return `<div class="exercise"><div class="exercise-head"><div><h3>${esc(name)}</h3><div class="muscle-line"><b>${esc(e.primary)}</b> · ${esc(e.secondary)}</div></div><div class="tags"><span class="tag">${esc(e.sets)}</span><span class="tag">RIR ${esc(e.rir)}</span></div></div><p>${esc(e.tech)}</p><div class="rest"><b>Set arası:</b> ${esc(e.setRest)} &nbsp; <b>Hareket arası:</b> ${esc(e.exerciseRest)}</div><div class="videos">${videoLinks(e)}</div>${log?`<div class="set-log">${rows}</div>`:''}</div>`}
function dashboard(){const last=state.bodyLogs.length?state.bodyLogs[state.bodyLogs.length-1]:null;const t=nextWorkout(),x=window.TRAINING[t];return shell('Dashboard',`<div class="hero"><div class="panel next"><div class="eyebrow">SIRADAKİ ANTRENMAN</div><h2>${esc(t)}</h2><p>${esc(x.focus)}</p><p class="muted">Program takvim gününe bağlı değildir. Kaçırılan gün varsa sıradaki seans devam eder.</p><button class="btn" id="startNext">Antrenmana Başla</button></div><div class="panel"><div class="label">SON OMRON / VÜCUT KOMPOZİSYONU</div><div class="grid-2"><div><div class="label">Yağ</div><strong>${esc(last?.fat||'—')} %</strong></div><div><div class="label">İskelet kası</div><strong>${esc(last?.skeletalMuscle||'—')} %</strong></div><div><div class="label">Kilo</div><strong>${esc(last?.weight||state.weight||'—')} kg</strong></div><div><div class="label">Kaynak</div><strong>${esc(last?.source||'—')}</strong></div></div><div class="muted small-note">Son ölçüm: ${esc(last?.date||'—')}</div></div></div><div class="grid"><div class="panel metric"><div class="label">Program</div><strong>6-Day A/B</strong></div><div class="panel metric"><div class="label">Protein</div><strong>140–185 g</strong></div><div class="panel metric"><div class="label">Set log</div><strong>${state.logs.length}</strong></div><div class="panel metric"><div class="label">Body log</div><strong>${state.bodyLogs.length}</strong></div></div><h3 class="section-title">Omron / Body Composition</h3><div class="panel"><div class="omron-grid"><div><img src="assets/omron-2026-08-20.png" class="omron-img" alt="Omron ekran görüntüsü"></div><div><p><b>20 Ağustos 2026 • 13:37</b></p><p class="muted">Omron ekranından işlenen değerler: Yağ %23,7 · İskelet kası %33,7. İskelet kası bu ekranda yüzde; kg değildir.</p><div class="log-row"><input id="bweight" class="input" type="number" step=".1" placeholder="Kilo kg"><input id="bfat" class="input" type="number" step=".1" placeholder="Yağ %"><input id="bmuscle" class="input" type="number" step=".1" placeholder="İskelet kası %"><input id="bwaist" class="input" type="number" step=".1" placeholder="Bel cm"><button class="btn" id="saveBody">Yeni ölçümü kaydet</button></div></div></div></div>`)}
function trainingPage(){const name=nextWorkout(),x=window.TRAINING[name];return shell('Training',`<div class="panel"><div class="eyebrow">PROGRAM SIRASI</div><h2>${esc(name)}</h2><p><b>Odak:</b> ${esc(x.focus)}</p><p class="muted">Yalnızca bugünün ısınması + ana antrenman + Core gösterilir. Exercise Library ayrı veritabanıdır.</p><div class="summary-pill">${x.exercises.length} ana hareket • ${x.core.length} core • ${x.warmup.length} ısınma</div></div><h3 class="section-title">1. ISINMA</h3>${x.warmup.map(n=>exerciseCard(n,false)).join('')}<h3 class="section-title">2. ANA ANTRENMAN</h3>${x.exercises.map(n=>exerciseCard(n,true)).join('')}<h3 class="section-title">3. CORE</h3>${x.core.map(n=>exerciseCard(n,true)).join('')}<div class="complete-wrap"><button class="btn complete-btn" id="completeWorkout">Antrenmanı Tamamladım</button></div>`)}
function library(){let names=Object.keys(window.EXERCISES).sort((a,b)=>a.localeCompare(b,'tr'));return shell('Exercise Library',`<div class="panel"><div class="log-row"><input id="libSearch" class="input" placeholder="Hareket / kas ara"><select id="libCat" class="input"><option value="">Tüm kategoriler</option>${[...new Set(names.map(n=>window.EXERCISES[n].category))].sort((a,b)=>a.localeCompare(b,'tr')).map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><p class="muted">Merkezi egzersiz veritabanı. Programdan çıkarılan hareket burada silinmez; geçmiş loglar korunur.</p></div><div id="libraryList" class="exercise-grid">${names.map(n=>exerciseCard(n,false)).join('')}</div>`)}
function activities(){return shell('Activities',`<div class="panel"><h3>Serbest / Yaşam Aktivitesi</h3><p class="muted">Yürüyüş, yüzme, koşu, kürek, köpek gezdirme ve spontan aktiviteler. Mesafe tek başına Zone 2 değildir.</p><div class="log-row"><input id="actName" class="input" placeholder="Aktivite"><input id="actDur" class="input" placeholder="Süre dk"><input id="actDist" class="input" placeholder="Mesafe km"><input id="actHr" class="input" placeholder="Ort. HR"><button class="btn" id="saveAct">Kaydet</button></div></div><h3 class="section-title">Son aktiviteler</h3><div class="panel">${state.activities.slice(-20).reverse().map(a=>`<div class="activity-card"><b>${esc(a.name)}</b><span class="muted">${esc(a.date)} • ${esc(a.duration||'—')} dk • ${esc(a.distance||'—')} km • HR ${esc(a.hr||'—')}</span></div>`).join('')||'Henüz aktivite yok.'}</div>`)}
function progress(){return shell('Progress',`<div class="panel"><table class="table"><thead><tr><th>Tarih</th><th>Hareket</th><th>Set</th><th>kg</th><th>rep/m</th><th>RIR</th></tr></thead><tbody>${state.logs.slice(-50).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.name)}</td><td>${esc(x.set||'')}</td><td>${esc(x.kg)}</td><td>${esc(x.reps)}</td><td>${esc(x.rir)}</td></tr>`).join('')||'<tr><td colspan="6">Henüz kayıt yok.</td></tr>'}</tbody></table></div><h3 class="section-title">Vücut kompozisyonu</h3><div class="panel"><table class="table"><thead><tr><th>Tarih</th><th>Kilo</th><th>Yağ %</th><th>İskelet kası %</th><th>Bel</th><th>Kaynak</th></tr></thead><tbody>${state.bodyLogs.slice(-30).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.weight||'—')}</td><td>${esc(x.fat||'—')}</td><td>${esc(x.skeletalMuscle||'—')}</td><td>${esc(x.waist||'—')}</td><td>${esc(x.source||'Manuel')}</td></tr>`).join('')}</tbody></table></div>`)}
function nutrition(){return shell('Nutrition',`<div class="grid-2"><div class="panel"><div class="label">Protein hedefi</div><strong>${esc(window.NUTRITION.proteinTarget)}</strong></div><div class="panel"><div class="label">Master Bar</div><strong>Bulk • Energy • Protein-dense</strong></div></div><div class="panel">${window.NUTRITION.principles.map(x=>`<div class="notice">${esc(x)}</div>`).join('')}</div>`)}
function recovery(){return shell('Recovery',`<div class="panel">${['7+ saat uyku','Günlük adım','Zone 2','Mobilite','Hidrasyon'].map((x,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}> ${x}</label>`).join('')}</div>`)}
function render(page='dashboard'){const fn={dashboard,training:trainingPage,activities,library,progress,nutrition,recovery}[page]||dashboard;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.innerHTML=fn();bind()}
function bind(){document.querySelectorAll('.log').forEach(btn=>btn.onclick=()=>{const box=btn.parentElement,g=k=>box.querySelector(`[data-k="${k}"]`)?.value||'';state.logs.push({date:today(),name:btn.dataset.name,set:btn.dataset.set,kg:g('kg'),reps:g('reps'),rir:g('rir')});save();btn.textContent='✓';btn.disabled=true});document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{state.checks[x.dataset.check]=x.checked;save()});const c=document.getElementById('completeWorkout');if(c)c.onclick=()=>{state.lastWorkout=nextWorkout();save();render('dashboard')};const s=document.getElementById('startNext');if(s)s.onclick=()=>render('training');const sb=document.getElementById('saveBody');if(sb)sb.onclick=()=>{const v=id=>document.getElementById(id).value;state.bodyLogs.push({date:today(),dateISO:new Date().toISOString(),weight:v('bweight')||state.weight,fat:v('bfat'),skeletalMuscle:v('bmuscle'),waist:v('bwaist'),source:'Manuel'});if(v('bweight'))state.weight=v('bweight');if(v('bwaist'))state.waist=v('bwaist');save();render('dashboard')};const sa=document.getElementById('saveAct');if(sa)sa.onclick=()=>{const v=id=>document.getElementById(id).value;state.activities.push({date:today(),name:v('actName'),duration:v('actDur'),distance:v('actDist'),hr:v('actHr')});save();render('activities')};const q=document.getElementById('libSearch'),cat=document.getElementById('libCat');if(q)q.oninput=()=>filterLib(q.value,cat.value);if(cat)cat.onchange=()=>filterLib(q.value,cat.value)}
function filterLib(q,cat){const list=document.getElementById('libraryList');if(!list)return;list.innerHTML=Object.keys(window.EXERCISES).sort((a,b)=>a.localeCompare(b,'tr')).filter(n=>{const e=window.EXERCISES[n],text=[n,e.primary,e.secondary,e.category].join(' ').toLocaleLowerCase('tr');return(!q||text.includes(q.toLocaleLowerCase('tr')))&&(!cat||e.category===cat)}).map(n=>exerciseCard(n,false)).join('')||'<div class="panel muted">Eşleşen hareket bulunamadı.</div>'}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>render(b.dataset.page));const theme=document.getElementById('themeBtn');if(theme)theme.onclick=()=>document.body.classList.toggle('dark');
try{render('dashboard')}catch(err){app.innerHTML=`<div class="content"><div class="panel"><h2>Fitness Master yükleniyor</h2><p>Veri yapısı sıfırlanıyor. Sayfayı bir kez yenile.</p></div></div>`;try{localStorage.removeItem('fitnessMaster')}catch(e){}};
})();
