const app=document.getElementById('app');
const DEFAULT={weight:85,waist:'',logs:[],bodyLogs:[],activities:[],checks:{},lastWorkout:null,pendingOmron:[]};
const state=Object.assign(DEFAULT,JSON.parse(localStorage.getItem('fitnessMaster')||'{}'));
const save=()=>localStorage.setItem('fitnessMaster',JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function shell(title,body){return `<div class="content"><h2>${title}</h2>${body}</div>`}
function todayWorkout(){return state.lastWorkout?nextWorkout():PROGRAM_ORDER[0]}
function nextWorkout(){let i=PROGRAM_ORDER.indexOf(state.lastWorkout);return PROGRAM_ORDER[(i+1)%PROGRAM_ORDER.length]}
function videos(e){return (e.videos||[]).map((v,i)=>`<a class="video" target="_blank" rel="noopener" href="${v}">▶ Video ${i+1}</a>`).join('')}
function exerciseCard(name,log=true){const e=EXERCISES[name];if(!e)return '';return `<div class="exercise"><h3>${esc(name)}</h3><div class="tags"><span class="tag">${esc(e.category)}</span><span class="tag">Ana: ${esc(e.primary)}</span><span class="tag">İkincil: ${esc(e.secondary)}</span><span class="tag">${esc(e.sets)}</span><span class="tag">RIR ${esc(e.rir)}</span></div><p>${esc(e.tech)}</p><div><b>Set dinlenmesi:</b> ${esc(e.setRest)} &nbsp; <b>Hareket arası:</b> ${esc(e.exerciseRest)}</div><div>${videos(e)}</div>${log?`<div class="log-row"><input class="input" placeholder="kg" data-k="kg"><input class="input" placeholder="tekrar / m" data-k="reps"><input class="input" placeholder="RIR" data-k="rir"><button class="btn log" data-name="${esc(name)}">Kaydet</button></div>`:''}</div>`}
function dashboard(){let last=state.bodyLogs.at(-1);return shell('Dashboard',`<div class="hero"><div class="panel"><div class="eyebrow">SIRADAKİ ANTRENMAN</div><h2>${esc(todayWorkout())}</h2><p class="muted">Takvim gününe bağlı değildir. Kaçırdığın gün olursa kaldığın yerden devam eder.</p><button class="btn" id="startNext">Antrenmana Başla</button></div><div class="panel"><div class="label">Vücut Kompozisyonu — son kayıt</div><div class="grid-2"><div><div class="label">Kilo</div><strong>${esc(last?.weight||state.weight)} kg</strong></div><div><div class="label">Yağ</div><strong>${esc(last?.fat||'—')} %</strong></div><div><div class="label">Kas</div><strong>${esc(last?.muscle||'—')} kg</strong></div><div><div class="label">Bel</div><strong>${esc(last?.waist||state.waist||'—')} cm</strong></div></div></div></div><div class="grid"><div class="panel metric"><div class="label">Program</div><strong>6-Day A/B</strong></div><div class="panel metric"><div class="label">Protein</div><strong>140–185 g</strong></div><div class="panel metric"><div class="label">Body log</div><strong>${state.bodyLogs.length}</strong></div><div class="panel metric"><div class="label">Antrenman log</div><strong>${state.logs.length}</strong></div></div><h3 class="section-title">Günlük Omron / Vücut Kompozisyonu</h3><div class="panel"><p class="muted">Omron ekran görüntüsünü gönderirsen, ekrandaki alanları bu forma göre eşleştirebiliriz. Şimdilik verileri manuel kaydedebilirsin.</p><div class="log-row"><input id="bweight" class="input" type="number" step=".1" placeholder="Kilo kg"><input id="bfat" class="input" type="number" step=".1" placeholder="Yağ %"><input id="bmuscle" class="input" type="number" step=".1" placeholder="Kas kg"><input id="bwaist" class="input" type="number" step=".1" placeholder="Bel cm"><button class="btn" id="saveBody">Bugünü Kaydet</button></div><div class="log-row"><input id="omronShot" class="input" type="file" accept="image/*"><button class="btn" id="saveShot">Omron Ekranını Bekleyen Kayıt Olarak Ekle</button></div></div>`)}
function training(){let name=todayWorkout(),x=TRAINING[name];return shell('Training',`<div class="panel"><div class="eyebrow">SIRADAKİ</div><h2>${esc(name)}</h2><div class="muted">${esc(x.focus)}</div><button class="btn" id="completeWorkout">Antrenmanı Tamamladım</button></div>${x.warmup?`<h3 class="section-title">1. ISINMA</h3>${x.warmup.map(exerciseCard).join('')}`:''}<h3 class="section-title">${x.warmup?'2.':'1.'} ANA ANTRENMAN</h3>${x.exercises.map(exerciseCard).join('')} ${x.core?.length?`<h3 class="section-title">3. CORE</h3>${x.core.map(exerciseCard).join('')}`:''}`)}
function library(){let names=Object.keys(EXERCISES);return shell('Exercise Library',`<div class="panel"><div class="log-row"><input id="libSearch" class="input" placeholder="Hareket / kas ara"><select id="libCat" class="input"><option value="">Tüm kategoriler</option>${[...new Set(names.map(n=>EXERCISES[n].category))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div></div><div id="libraryList" class="exercise-grid">${names.sort((a,b)=>a.localeCompare(b,'tr')).map(n=>exerciseCard(n,false)).join('')}</div>`)}
function activities(){return shell('Activities',`<div class="panel"><h3>Serbest / Yaşam Aktivitesi</h3><p class="muted">Yürüyüş, yüzme, kürek, koşu, köpek gezdirme, spor vb. Buraya kaydedilir. Mesafe tek başına Zone 2 anlamına gelmez; yoğunluk HR ve aktivite verileriyle değerlendirilir.</p><div class="log-row"><input id="actName" class="input" placeholder="Aktivite"><input id="actDur" class="input" placeholder="Süre dk"><input id="actDist" class="input" placeholder="Mesafe km"><input id="actHr" class="input" placeholder="Ort. HR"><button class="btn" id="saveAct">Kaydet</button></div></div><h3 class="section-title">Son aktiviteler</h3><div class="panel">${state.activities.slice(-20).reverse().map(a=>`<div class="activity-card"><span><b>${esc(a.name)}</b><br><span class="muted">${esc(a.date)} • ${esc(a.duration||'—')} dk • ${esc(a.distance||'—')} km • HR ${esc(a.hr||'—')}</span></span></div>`).join('')||'Henüz aktivite yok.'}</div>`)}
function progress(){return shell('Progress',`<div class="panel"><table class="table"><thead><tr><th>Tarih</th><th>Hareket</th><th>kg</th><th>rep</th><th>RIR</th></tr></thead><tbody>${state.logs.slice(-30).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.name)}</td><td>${esc(x.kg)}</td><td>${esc(x.reps)}</td><td>${esc(x.rir)}</td></tr>`).join('')||'<tr><td colspan="5">Henüz kayıt yok.</td></tr>'}</tbody></table></div><h3 class="section-title">Vücut kompozisyonu</h3><div class="panel"><table class="table"><thead><tr><th>Tarih</th><th>Kilo</th><th>Yağ %</th><th>Kas kg</th><th>Bel</th></tr></thead><tbody>${state.bodyLogs.slice(-30).reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.weight)}</td><td>${esc(x.fat)}</td><td>${esc(x.muscle)}</td><td>${esc(x.waist)}</td></tr>`).join('')||'<tr><td colspan="5">Henüz body log yok.</td></tr>'}</tbody></table></div>`)}
function nutrition(){return shell('Nutrition',`<div class="grid-2"><div class="panel"><div class="label">Protein hedefi</div><strong>${NUTRITION.proteinTarget}</strong></div><div class="panel"><div class="label">Master Bar</div><strong>Bulk • Energy • Protein-dense</strong></div></div><div class="panel">${NUTRITION.principles.map(x=>`<div class="notice">${esc(x)}</div>`).join('')}</div>`)}
function recovery(){return shell('Recovery',`<div class="panel">${['7+ saat uyku','Günlük adım','Zone 2','Mobilite','Hidrasyon'].map((x,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}> ${x}</label>`).join('')}</div>`)}
function render(page='dashboard'){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.innerHTML={dashboard,training,activities,library,progress,nutrition,recovery}[page]();bind(page)}
function bind(page){document.querySelectorAll('.log').forEach(btn=>btn.onclick=()=>{let box=btn.parentElement,g=k=>box.querySelector(`[data-k="${k}"]`)?.value||'';state.logs.push({date:new Date().toLocaleDateString('tr-TR'),name:btn.dataset.name,kg:g('kg'),reps:g('reps'),rir:g('rir')});save();btn.textContent='Kaydedildi';setTimeout(()=>btn.textContent='Kaydet',800)});document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{state.checks[x.dataset.check]=x.checked;save()});let c=document.getElementById('completeWorkout');if(c)c.onclick=()=>{state.lastWorkout=todayWorkout();save();render('dashboard')};let s=document.getElementById('startNext');if(s)s.onclick=()=>render('training');let sb=document.getElementById('saveBody');if(sb)sb.onclick=()=>{let v=id=>document.getElementById(id).value;state.bodyLogs.push({date:new Date().toLocaleDateString('tr-TR'),weight:v('bweight')||state.weight,fat:v('bfat'),muscle:v('bmuscle'),waist:v('bwaist')||state.waist});state.weight=v('bweight')||state.weight;state.waist=v('bwaist')||state.waist;save();render('dashboard')};let ss=document.getElementById('saveShot');if(ss)ss.onclick=()=>{let f=document.getElementById('omronShot').files[0];if(!f)return alert('Önce Omron ekran görüntüsünü seç.');state.pendingOmron.push({date:new Date().toLocaleDateString('tr-TR'),name:f.name,status:'Analiz bekliyor'});save();alert('Ekran görüntüsü yerel olarak bekleyen kayıt listesine eklendi.');};let sa=document.getElementById('saveAct');if(sa)sa.onclick=()=>{let v=id=>document.getElementById(id).value;state.activities.push({date:new Date().toLocaleDateString('tr-TR'),name:v('actName'),duration:v('actDur'),distance:v('actDist'),hr:v('actHr')});save();render('activities')};let q=document.getElementById('libSearch'),cat=document.getElementById('libCat');if(q)q.oninput=()=>filterLib(q.value,cat.value);if(cat)cat.onchange=()=>filterLib(q.value,cat.value)}
function filterLib(q,cat){let list=document.getElementById('libraryList');if(!list)return;list.innerHTML=Object.keys(EXERCISES).sort((a,b)=>a.localeCompare(b,'tr')).filter(n=>(!q||n.toLowerCase().includes(q.toLowerCase())||EXERCISES[n].primary.toLowerCase().includes(q.toLowerCase()))&&(!cat||EXERCISES[n].category===cat)).map(n=>exerciseCard(n,false)).join('')||'<div class="panel">Sonuç yok.</div>'}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>render(b.dataset.page));document.getElementById('themeBtn').onclick=()=>document.body.classList.toggle('dark');render();
