/* Fitness Master — Program page: Push 1 default + manual six-workout selector. */
(function(){'use strict';
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
const O=['Push 1','Pull 1','Legs 1','Push 2','Pull 2','Legs 2'];
function P(){return window.FitnessMasterCurated?.PROGRAMS||{};}
function card(n){return typeof EXERCISES!=='undefined'&&EXERCISES[n]&&typeof exerciseCard==='function'?exerciseCard(n,false):`<div class="exercise"><h3>${esc(n)}</h3></div>`;}
function page(name){const p=P(),x=p[name]||p['Push 1'];return `<div class="content"><h2>Program</h2><div class="panel"><div class="eyebrow">MASTER PROGRAM</div><h2>${esc(name)}</h2><p><b>Odak:</b> ${esc(x.focus)}</p><div class="log-row"><label class="label" style="align-self:center">Program seç</label><select id="programSelect" class="input">${O.map(n=>`<option value="${esc(n)}" ${n===name?'selected':''}>${esc(n)}</option>`).join('')}</select></div><p class="muted">Program ekranı bağımsızdır. Buradan 6 program arasında gezebilirsin; Training ise Progress'teki son antrenmana göre bir sonraki seansı otomatik açar.</p></div><h3 class="section-title">1. ISINMA</h3>${(x.warmup||[]).map(card).join('')}<h3 class="section-title">2. ANA ANTRENMAN</h3>${(x.exercises||[]).map(card).join('')}<h3 class="section-title">3. CORE</h3>${(x.core||[]).map(card).join('')}${x.zone2?'<h3 class="section-title">4. CARDIO</h3><div class="panel"><b>ZONE 2 — 25–30 dk</b><p class="muted">Kişisel cihaz Zone 2 verisi veya konuşma testi kullanılır; sabit bpm hedefi kullanılmaz.</p></div>':''}</div>`;}
function show(name){const app=document.getElementById('app');if(!app)return;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='program'));const selected=name||'Push 1';app.innerHTML=page(selected);const sel=document.getElementById('programSelect');if(sel)sel.onchange=()=>show(sel.value);}
function install(){const b=document.querySelector('.nav-btn[data-page="program"]');if(b)b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();show('Push 1');};window.FitnessMasterProgram={show,order:()=>O,latestWorkoutFromHistory:()=>null,nextWorkout:()=>null};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
