/* Fitness Master — Training: resume in-progress session, otherwise show next completed-session workout. */
(function(){'use strict';
const O=['Push 1','Pull 1','Legs 1','Push 2','Pull 2','Legs 2'];
function P(){return window.FitnessMasterCurated?.PROGRAMS||{};}
function norm(s){return String(s||'').toLowerCase().replace(/[–—]/g,'-').replace(/\s+/g,' ').trim();}
function read(){try{return JSON.parse(localStorage.getItem('fitnessMaster')||'{}');}catch(e){return {};}}
function write(s){localStorage.setItem('fitnessMaster',JSON.stringify(s));if(window.FitnessMasterFirebaseSync?.pushNow)window.FitnessMasterFirebaseSync.pushNow();}
function dateNow(){return new Date().toLocaleDateString('tr-TR');}
function dv(d){const p=String(d||'').split(/[.\/-]/).map(Number);return p.length===3?new Date(p[2],p[1]-1,p[0]).getTime():0;}
function sid(w,d){return `session-${String(d).replace(/[^0-9]/g,'')}-${w.replace(/\s+/g,'-').toLowerCase()}`;}
function latestCompleted(){const s=read(),a=Array.isArray(s.workoutSessions)?s.workoutSessions:[],done=a.filter(x=>x&&x.status==='completed');return done.slice().sort((a,b)=>dv(b.date)-dv(a.date)||String(b.completedAt||'').localeCompare(String(a.completedAt||'')))[0]||null;}
function inProgress(){const s=read(),a=Array.isArray(s.workoutSessions)?s.workoutSessions:[];return a.filter(x=>x&&x.status==='in_progress').sort((a,b)=>String(b.updatedAt||b.startedAt||'').localeCompare(String(a.updatedAt||a.startedAt||'')))[0]||null;}
function next(){const p=inProgress();if(p?.workout)return p.workout;const l=latestCompleted()?.workout;return l?O[(O.indexOf(l)+1)%O.length]:O[0];}
function ensureSession(w){const s=read(),a=Array.isArray(s.workoutSessions)?s.workoutSessions:[],d=dateNow(),id=sid(w,d);let x=a.find(q=>q&&q.id===id);if(!x){x={id,date:d,workout:w,status:'in_progress',startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};a.push(x);s.workoutSessions=a;write(s);}else if(x.status==='in_progress'){x.updatedAt=new Date().toISOString();s.workoutSessions=a;localStorage.setItem('fitnessMaster',JSON.stringify(s));}document.body.dataset.fmWorkout=w;document.body.dataset.fmSessionId=id;return x;}
function latest(){return latestCompleted()?.workout||null;}
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function card(n,log){return typeof EXERCISES!=='undefined'&&EXERCISES[n]&&typeof exerciseCard==='function'?exerciseCard(n,!!log):`<div class="exercise"><h3>${esc(n)}</h3></div>`;}
function render(){const app=document.getElementById('app');if(!app)return;const p=P(),name=next(),x=p[name];if(!x)return;const session=ensureSession(name),last=latestCompleted();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='training'));app.innerHTML=`<div class="content"><h2>Training</h2><div class="panel"><div class="eyebrow">${session.status==='in_progress'?'RESUME SESSION':'NEXT SESSION'}</div><h2>${esc(name)}</h2><p><b>Progress'teki son tamamlanan antrenman:</b> ${esc(last?.workout||'Henüz kayıt yok')}</p><p><b>Odak:</b> ${esc(x.focus)}</p></div><h3 class="section-title">1. ISINMA</h3>${x.warmup.map(n=>card(n,false)).join('')}<h3 class="section-title">2. ANA ANTRENMAN</h3>${x.exercises.map(n=>card(n,true)).join('')}<h3 class="section-title">3. CORE</h3>${x.core.map(n=>card(n,true)).join('')}${x.zone2?'<div class="panel"><h3>ZONE 2</h3><p>25–30 dk · kişisel cihaz Zone 2 / konuşma testi</p></div>':''}<div class="complete-wrap"><button class="btn complete" id="completeWorkout">Antrenmanı Tamamladım</button></div></div>`;}
function install(){document.addEventListener('click',e=>{const b=e.target.closest('.nav-btn[data-page="training"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();render();},true);window.FitnessMasterTraining={render,nextWorkout:next,latestWorkout:latest,ensureSession};window.addEventListener('fm-cloud-data-updated',()=>{if(document.querySelector('.nav-btn.active[data-page="training"]'))render();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();
